### ISSUE TITLE
Any

### ISSUE THREAD

**Issue by IanaKhitsko** [BogdanShaposhnik/EuroDiffusion#2]
https://github.com/BogdanShaposhnik/EuroDiffusion/blob/ed0a8b93cb4a09d56f61364ac00ce0e366c199e8/Processor.cs#L147

Can you use "any" or "some" for 2-dimension array in cs? Thus the method will look more elegant

**Comment by BogdanShaposhnik** [comment]
It is not possible to use any for 2-dimension, but it is possible to use foreach to go through elements.
