### ISSUE TITLE
City.cs

### ISSUE THREAD

**Issue by IanaKhitsko** [BogdanShaposhnik/EuroDiffusion#3]
https://github.com/BogdanShaposhnik/EuroDiffusion/blob/ed0a8b93cb4a09d56f61364ac00ce0e366c199e8/City.cs#L9

Why the class is Town the file is City? (yeah, i can imagine that to rename all methods and classes in someone's code it is another job, but still pay attention to file naming as well)

**Comment by BogdanShaposhnik** [comment]
renamed Town to City
